### ISSUE TITLE
Blocked API call

### ISSUE THREAD

**Issue by bmkopp10** [eyecatchup/node-aaf-api#1]
For the life of me I can't get past ...

Access to fetch at 'https://api.platform.aaf.com/v1/graphql' from origin 'http://localhost:4200' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I'm assuming it's because I'm not sending over headers? Please help!

**Comment by bmkopp10** [comment]
My site is built in Angular.  I have the Request dependency.  I tried changing the 'User-Agent' in node_modules to something custom.  I'm just so lost on whether there is something else I need to do? Or if this is an actual bug.

**Comment by bmkopp10** [comment]
```js
import { Injectable } from '@angular/core';
import { AngularFirestore, AngularFirestoreCollection } from 'angularfire2/firestore';
import { Observable, BehaviorSubject, of } from 'rxjs';
import { map } from 'rxjs/operators';
const aafApi = require('node-aaf-api');
import * as aafApi from 'node-aaf-api';
import { QB } from '../../shared/data/qb';
import { RB } from '../../shared/data/rb';
import { WR } from '../../shared/data/wr';
import { TE } from '../../shared/data/te';
import { games } from '../../shared/data/games';
import { gameData } from '../../shared/data/gameData';

@Injectable()
export class FantasyService {
  teamCollection: AngularFirestoreCollection<any>;
  playerCollection: AngularFirestoreCollection<any>;
  userCollection: AngularFirestoreCollection<any>;
  activityCollection: AngularFirestoreCollection<any>;
  scheduleCollection: AngularFirestoreCollection<any>;
  waiverDates: any = [1550052000000, 1550656800000, 1551261600000, 1551866400000, 1552467600000, 1553072400000, 1553677200000, 1554282000000, 1554886800000, 1555491600000]

  constructor(
    private afs: AngularFirestore,
  ) {
    this.teamCollection = this.afs.collection('teams');
    this.playerCollection = this.afs.collection('players', (ref) => ref.orderBy('last', 'asc'));
    this.userCollection = this.afs.collection('users');
    this.activityCollection = this.afs.collection('activity', (ref) => ref.orderBy('timestamp', 'desc'));
    this.scheduleCollection = this.afs.collection('schedule');
    this.getStats()
  }
  getStats () {
    let gameId = 'GjoCxWXQfvKpZuFlqeOgB5I-ceJn';
    aafApi.getFullGameStatsByPlayer(gameId, (response) => {
        if (response.status === 'error') {
            throw new Error(response.data);
        } else {
            console.log(response.data.node.playersConnection.edges);
        }
    });
  }
}
```

**Comment by ccbrown** [comment]
The cache-control header currently isn't allowed on cross-origin requests. This line should probably be removed from the library:

https://github.com/eyecatchup/node-aaf-api/blob/2df5d1df72236e087af07ea55eec6f5501de633e/index.js#L11

Even outside of the browser, there's no advantage to explicitly specifying "no-cache" for the AAF API.

**Comment by bmkopp10** [comment]
Worked like a charm! Thanks!

**Comment by eyecatchup** [comment]
I removed the `cache-control` header.

**Comment by bmkopp10** [comment]
In Safari I get this error.

Fetch API cannot load https://api.platform.aaf.co... due to access control checks. Any idea?

curl 'https://api.platform.aaf.co... \
-XPOST \
-H 'Content-Type: application/json' \
-H 'User-Agent: node-aaf-api (https://github.com/eyecatch... \
-H 'Accept: application/json' \
-H 'Origin: http://localhost:4200' \
-H 'Referer: http://localhost:4200/team' \

Works fine on Chrome and Brave browsers.  Though it doesn't work on Chrome on my phone.

**Comment by ccbrown** [comment]
I think this is another Access-Control-Request-Headers problem. We're going to deploy an API update soon that will probably make this issue go away.
